### ISSUE TITLE
reset airbyte connections

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/prefect-proxy#124]

**Comment by Rishikesh63** [comment]
@fatchat  
 uvicorn proxy.main:app --workers 4 --host 0.0.0.0 --port 8001
after running this command i get error:-
>>
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     Started parent process [20052]
Process SpawnProcess-3:
Process SpawnProcess-2:
Process SpawnProcess-1:
Process SpawnProcess-4:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
Traceback (most recent call last):
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module     
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module     
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in <module>
    from proxy.service import (
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in <module>
    from proxy.prefect_flows import deployment_schedule_flow_v4
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in <module>
    from proxy.service import (
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in <module>
    from prefect_airbyte.flows import reset_connection
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module     
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module     
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in <module>
    from proxy.prefect_flows import deployment_schedule_flow_v4
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in <module>
    from prefect_airbyte.flows import reset_connection
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in <module>
    from proxy.service import (
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in <module>
    from proxy.prefect_flows import deployment_schedule_flow_v4
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in <module>
    from prefect_airbyte.flows import reset_connection
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in <module>
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in <module>
    from proxy.prefect_flows import deployment_schedule_flow_v4
  File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in <module>
    from prefect_airbyte.flows import reset_connection
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)     

please guide me how i can solve this problem

**Comment by fatchat** [comment]
i already answered this in the other issue you asked on ... please don't fill up the issues with pages of logs there is exactly one line in these logs which is relevant
`ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows'`

**Comment by Rishikesh63** [comment]
@fatchat  i am getting this error during airbyte connection , MySql->CSV(source to destination)
Configuration check failed
State code: 08S01; Message: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by fatchat** [comment]
@Rishikesh63 looks like a network problem

**Comment by Rishikesh63** [comment]
@fatchat  my network is ok ,i have confusion with host name and database name for MySql . I wants to know exactly what will we 
hostname and database name in source

**Comment by fatchat** [comment]
@Rishikesh63 i didn't mean your internet connectivity, i meant it looks like airbyte is having trouble connecting to either the source or the destination over your (local?) network. you should be able to find instructions for airbyte's mysql connectors in their public documentation

**Comment by Rishikesh63** [comment]
I have followed all the instructions given in documentation still I am
getting error

**Comment by Rishikesh63** [comment]
@fatchat   i connected MySQL to Local CSV but in streams selection there doesn't shows any streams
